### PR TITLE
TEI concepts

### PR DESCRIPTION
**Pull request by twagoo**
Based on request (via e-mail) by CLARIN-DK (@meaton)

### CODE REVIEW

**Comment by twagoo** [comment]
Excerpt from e-mail exchange:

> (..) The "notes statement" [1] and "anonymous block type" [2] concept links are there.  They just don't show up in the component registry, which is obviously a bug. Fooled by my own code...
>
> However we currently still need the XPaths in the mapping as explained in my previous mail. However if we get around to implementing support for concept contexts this profile can be handled without adaptations.
> (..)
>[1] http://hdl.handle.net/11459/CCR_C-5370_fc371ccd-3330-f1c2-6f87-aa363efe4b32
>[2] http://hdl.handle.net/11459/CCR_C-6179_dd15ee79-064c-c53d-fa3a-9bbacb7b2db4

See [availability component](https://catalog.clarin.eu/ds/ComponentRegistry#/?itemId=clarin.eu%3Acr1%3Ac_1375880372986&registrySpace=public). Whitelisting approach can be used instead of pure XPath? (@menzowindhouwer, @teckart)

**Comment by menzowindhouwer** [comment]
We could try out the `<acceptableContext>` construct. This allows to say which ConceptLinks on enclosing components are acceptable. And also allow empty context. A problem can be that there are other contextual ConceptLinks that we don't know yet. They have to be explicitly accepted, or we have to go in the code and make the context white/black list potentially more concept specific:
`<facetConcept><concept><acceptableContext><concept/></><rejectableContext><concept/></></></>`

**Comment by twagoo** [comment]
> We could try out the `<acceptableContext>` construct. 
Interesting, I think we should try this. I see we are already using this for language code. 
I don't understand the "also allow empty context" part: the concepts on these attributes are too generic to be mapped to availability without this specific context.

**Comment by menzowindhouwer** [comment]
Now we don't take context (ConceptLinks on enclosing components) into account. So currently matches on a concept can have: no ConceptLinks on enclosing components (which is referred to as an empty context), or some. An acceptable context lists the concepts which are allowed. However, you can also indicate what to do when there are no concepts in the context: `includeEmpty="true"` states that an empty context is also acceptable.

You stated that these new concepts are generic and thus need to restricted by context, i.e., in their case an acceptable context needs to be defined. However, currently before we didn't deal with context so the previous list of concepts must have been more specific and any (incl. an empty) context was acceptable. So I guess in the end we'll need to have the ability to state the acceptable/rejectable context per concept. But we can do a first experiment with the global acceptable context ...

**Comment by twagoo** [comment]
Now I understand. I guess the only way of checking this is by running an import with and without including empty context.

It would be nice if the acceptable context could be scoped to individual concepts or sets of concepts (rather than the entire facet).

**Comment by twagoo** [comment]
Superseded by https://github.com/clarin-eric/VLO-mapping/pull/1 (`facetConcepts.xml` has moved to VLO-mapping project, see #22)

**Comment by twagoo** [comment]
The `<acceptableContext>` solution will not be part of the default mapping for 4.1.0 but can be tried out later (in the VLO-mapping project), and if successful applied to the VLO as of 4.1.0 because of "dynamic" (detached) facet mapping (see #22).

**Pull request closed without merging**
